---
game_file: "dominion"
game_class: "Dominion"
max_players: 4
min_players: 2
zones:
    - name: "hand"
      owner: "player"
    - name: "deck"
      owner: "player"
    - name: "discard"
      owner: "player"
    - name: "play_zone"
      owner: "player"
    - name: "kingdom"
      zone_type: "supply"
      multiplicity: 10
    - name: "treasure"
      zone_type: "supply"
      multiplicity: 3
    - name: "victory"
      zone_type: "supply"
      multiplicity: 3
    - name: "curses"
      zone_type: "supply"
    - name: "trash"
card_set:
    - name: "Copper"
      front_face: "/static/deckr/cards/copper.jpg"
      back_face: "/static/deckr/cards/b1fv.png"
      card_type: ["treasure"]
      kingdom_card: False
      effect: "Provides 1 Coin."
      cost: 0
      value: 1

    - name: "Silver"
      front_face: "/static/deckr/cards/silver.jpg"
      back_face: "/static/deckr/cards/b1fv.png"
      card_type: ["treasure"]
      kingdom_card: False
      effect: "Provides 2 Coins."
      cost: 3
      value: 2

    - name: "Gold"
      front_face: "/static/deckr/cards/gold.jpg"
      back_face: "/static/deckr/cards/b1fv.png"
      card_type: ["treasure"]
      kingdom_card: False
      effect: "Provides 3 Coins."
      cost: 6
      value: 3

    - name: "Estate"
      front_face: "/static/deckr/cards/estate.jpg"
      back_face: "/static/deckr/cards/b1fv.png"
      card_type: ["victory"]
      kingdom_card: False
      cost: 2
      victory_points: 1
      effect: "Provides 1 VP."

    - name: "Duchy"
      front_face: "/static/deckr/cards/duchy.jpg"
      back_face: "/static/deckr/cards/b1fv.png"
      card_type: ["victory"]
      kingdom_card: False
      effect: "Provides 3 VP."
      cost: 5
      victory_points: 2

    - name: "Province"
      front_face: "/static/deckr/cards/province.jpg"
      back_face: "/static/deckr/cards/b1fv.png"
      card_type: ["victory"]
      kingdom_card: False
      effect: "Provides 6 VP."
      cost: 8
      victory_points: 6

    - name: "Curse"
      front_face: "/static/deckr/cards/curse.jpg"
      back_face: "/static/deckr/cards/b1fv.png"
      card_type: ["curse"]
      kingdom_card: False
      effect: "Provides -1 VP." 
      cost: 0
      victory_points: -1

    # Begin kindgom cards
    - name: "Cellar"
      front_face: "/static/deckr/cards/cellar.jpg"
      back_face: "/static/deckr/cards/b1fv.png"
      card_type: ["action"]
      kingdom_card: True
      effect: "+1 Action / Discard any number of cards. +1 Card per card discarded."
      cost: 2

    - name: "Chapel"
      front_face: "/static/deckr/cards/chapel.jpg"
      back_face: "/static/deckr/cards/b1fv.png"
      card_type: ["action"]
      kingdom_card: True
      effect: "Trash up to 4 cards from your hand."
      cost: 2

    - name: "Moat"
      front_face: "/static/deckr/cards/moat.jpg"
      back_face: "/static/deckr/cards/b1fv.png"
      card_type: ["action", "reaction"]
      kingdom_card: True
      effect: "+2 Cards / When another player plays an Attack card, you may reveal this from your hand. If you do, you are unaffected by that Attack."
      cost: 2

    - name: "Chancellor"
      front_face: "/static/deckr/cards/chancellor.jpg"
      back_face: "/static/deckr/cards/b1fv.png"
      card_type: ["action"]
      effect: "+2 Coins / You may immediately put your deck into your discard pile."
      kingdom_card: True
      cost: 3

    - name: "Village"
      front_face: "/static/deckr/cards/village.jpg"
      back_face: "/static/deckr/cards/b1fv.png"
      card_type: ["action"]
      kingdom_card: True
      effect: "+1 Card, +2 Actions."
      cost: 3

    - name: "Woodcutter"
      front_face: "/static/deckr/cards/woodcutter.jpg"
      back_face: "/static/deckr/cards/b1fv.png"
      card_type: ["action"]
      kingdom_card: True
      effect: "+1 Buy, +2 Coins."
      cost: 3

    - name: "Workshop"
      front_face: "/static/deckr/cards/workshop.jpg"
      back_face: "/static/deckr/cards/b1fv.png"
      card_type: ["action"]
      kingdom_card: True
      effect: "Gain a card costing up to 4 Coins."
      cost: 3

    - name: "Bureaucrat"
      front_face: "/static/deckr/cards/bureaucrat.jpg"
      back_face: "/static/deckr/cards/b1fv.png"
      card_type: ["action"]
      kingdom_card: True
      effect: "Gain a Silver card, put it on top of your deck. Each other player reveals a Victory card and puts it on top of his deck. (or reveals a hand with no Victory cards)."
      cost: 4

    - name: "Feast"
      front_face: "/static/deckr/cards/feast.jpg"
      back_face: "/static/deckr/cards/b1fv.png"
      card_type: ["action"]
      kingdom_card: True
      effect: "Trash this card. Gain a card costing up to 5 Coins."
      cost: 4

    - name: "Gardens"
      front_face: "/static/deckr/cards/gardens.jpg"
      back_face: "/static/deckr/cards/b1fv.png"
      card_type: ["victory"]
      kingdom_card: True
      effect: "Worth 1 VP for every 10 cards in your deck (rounded down)."
      cost: 4

    - name: "Militia"
      front_face: "/static/deckr/cards/militia.jpg"
      back_face: "/static/deckr/cards/b1fv.png"
      card_type: ["action", "attack"]
      kingdom_card: True
      effect: "+2 Coins. Each other player discards down to 3 cards in his hand."
      cost: 4

    - name: "Moneylender"
      front_face: "/static/deckr/cards/moneylender.jpg"
      back_face: "/static/deckr/cards/b1fv.png"
      card_type: ["action"]
      kingdom_card: True
      effect: "Trash a Copper card from your hand. If you do, +3 Coins."
      cost: 4

    - name: "Remodel"
      front_face: "/static/deckr/cards/remodel.jpg"
      back_face: "/static/deckr/cards/b1fv.png"
      card_type: ["action"]
      kingdom_card: True
      effect: "Trash a card from your hand. Gain a card costing up to 2 Coins more than the trashed card."
      cost: 4

    - name: "Smithy"
      front_face: "/static/deckr/cards/smithy.jpg"
      back_face: "/static/deckr/cards/b1fv.png"
      card_type: ["action"]
      kingdom_card: True
      effect: "+3 Cards."
      cost: 4

    - name: "Spy"
      front_face: "/static/deckr/cards/spy.jpg"
      back_face: "/static/deckr/cards/b1fv.png"
      card_type: ["action", "attack"]
      kingdom_card: True
      effect: "+1 Card, +1 Action, Each player (including you) reveals the top card of his deck and either discards it or puts it back, your choice."
      cost: 4

    - name: "Thief"
      front_face: "/static/deckr/cards/thief.jpg"
      back_face: "/static/deckr/cards/b1fv.png"
      card_type: ["action", "attack"]
      kingdom_card: True
      effect: "Each other player reveals the top 2 cards of his deck. If they revealed any Treasure cards, they trash one of them that you choose. You may gain any or all of these trashed cards. They discard the other revealed cards."
      cost: 4

    - name: "Throne Room"
      front_face: "/static/deckr/cards/throneroom.jpg"
      back_face: "/static/deckr/cards/b1fv.png"
      card_type: ["action"]
      kingdom_card: True
      effect: "Choose an Action card in your hand. Play it twice."
      cost: 4

    - name: "Council Room"
      front_face: "/static/deckr/cards/councilroom.jpg"
      back_face: "/static/deckr/cards/b1fv.png"
      card_type: ["action"]
      kingdom_card: True
      effect: "+4 Cards, +1 Buy, Each other player draws a card."
      cost: 5

    - name: "Festival"
      front_face: "/static/deckr/cards/festival.jpg"
      back_face: "/static/deckr/cards/b1fv.png"
      card_type: ["action"]
      kingdom_card: True
      effect: "+2 Actions, +1 Buy, +2 Coins."
      cost: 5

    - name: "Laboratory"
      front_face: "/static/deckr/cards/laboratory.jpg"
      back_face: "/static/deckr/cards/b1fv.png"
      card_type: ["action"]
      kingdom_card: True
      effect: "+2 Cards, +1 Action."
      cost: 5

    - name: "Library"
      front_face: "/static/deckr/cards/library.jpg"
      back_face: "/static/deckr/cards/b1fv.png"
      card_type: ["action"]
      kingdom_card: True
      effect: "Draw until you have 7 cards in hand. You may set aside any Action cards drawn this way, as you draw them; discard the set aside cards after you finish drawing."
      cost: 5

    - name: "Market"
      front_face: "/static/deckr/cards/market.jpg"
      back_face: "/static/deckr/cards/b1fv.png"
      card_type: ["action"]
      kingdom_card: True
      effect: "+1 Card, +1 Action, +1 Buy, +1 Coin."
      cost: 5

    - name: "Mine"
      front_face: "/static/deckr/cards/mine.jpg"
      back_face: "/static/deckr/cards/b1fv.png"
      card_type: ["action"]
      kingdom_card: True
      effect: "Trash a Treasure card from your hand. Gain a Treasure card costing up to 3 Coins more; put it into your hand."
      cost: 5

    - name: "Witch"
      front_face: "/static/deckr/cards/witch.jpg"
      back_face: "/static/deckr/cards/b1fv.png"
      card_type: ["action"]
      kingdom_card: True
      effect: "+2 Cards, Each other player gains a Curse card."
      cost: 5

    - name: "Adventurer"
      front_face: "/static/deckr/cards/adventurer.jpg"
      back_face: "/static/deckr/cards/b1fv.png"
      card_type: ["action"]
      kingdom_card: True
      effect: "Reveal cards from your deck until you reveal 2 Treasure cards. Put those Treasure cards in your hand and discard the other revealed cards."
      cost: 6
