---
game_file: "magic"
game_class: "Magic"
max_players: 2
min_players: 2
zones:
    - name: "hand"
      owner: "player"
    - name: "library"
      owner: "player"
    - name: "graveyard"
      owner: "player"
    - name: "battlefield"
      owner: "player"
    # Command zone (not yet implemented)
    #- name: "command"
    #  owner: "player"

    - name: "stack"
    - name: "exile"

card_set:
    - name: "Forest"
      front_face: "/static/deckr/cards/magic/forest.jpg"
      back_face: "/static/deckr/cards/magic/back.jpg"
      types: ["Land"]
      ability: "{T}: add {G}"
    - name: "Island"
      front_face: "/static/deckr/cards/magic/island.jpg"
      back_face: "/static/deckr/cards/magic/back.jpg"
      types: ["Land"]
      ability: "{T}: add {U}"
    - name: "Mountain"
      front_face: "/static/deckr/cards/magic/mountain.jpg"
      back_face: "/static/deckr/cards/magic/back.jpg"
      types: ["Land"]
      ability: "{T}: add {R}"
    - name: "Swamp"
      front_face: "/static/deckr/cards/magic/swamp.jpg"
      back_face: "/static/deckr/cards/magic/back.jpg"
      types: ["Land"]
      ability: "{T}: add {B}"
    - name: "Plains"
      front_face: "/static/deckr/cards/magic/plains.jpg"
      back_face: "/static/deckr/cards/magic/back.jpg"
      types: ["Land"]
      ability: "{T}: add {W}"
