---
game_file: "solitaire"
game_class: "Solitaire"
max_players: 1
zones:
    - name: "victory_zone1"
      zone_type: "victory"
    - name: "victory_zone2"
      zone_type: "victory"
    - name: "victory_zone3"
      zone_type: "victory"
    - name: "victory_zone4"
      zone_type: "victory"
    - name: "play_zone1"
      zone_type: "play"
    - name: "play_zone2"
      zone_type: "play"
    - name: "play_zone3"
      zone_type: "play"
    - name: "play_zone4"
      zone_type: "play"
    - name: "play_zone5"
      zone_type: "play"
    - name: "play_zone6"
      zone_type: "play"
    - name: "play_zone7"
      zone_type: "play"
    - name: "deck"
      zone_type: "deck"
    - name: "deck_flipped"
      zone_type: "deck"