---
game_file: "solitaire"
game_class: "Solitaire"
max_players: 1
min_players: 1
game_zones:
    - name: "victory_zone"
      multiplicity: 4
      zone_type: "victory"
    - name: "play_zone"
      multiplicity: 7
      zone_type: "play"
    - name: "deck"
      zone_type: "deck"
    - name: "deck_flipped"
      zone_type: "deck"
